<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Raghuram" ignored="0" name="SymptomsDiary" tests="3" failures="1" timestamp="21 Jun 2017 20:40:26 GMT" time="55.288" errors="0">
  <testcase name="symptomsCreateOrderByDate" time="14.541" classname="com.medlink.Android.TestCase.SymptomsDiary"/>
  <testcase name="symptomsCreateOrderBySymptoms" time="11.436" classname="com.medlink.Android.TestCase.SymptomsDiary"/>
  <testcase name="symptomsDiaryDelete" time="5.261" classname="com.medlink.Android.TestCase.SymptomsDiary">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
	at com.medlink.Android.TestCase.SymptomsDiary.symptomsDiaryDelete(SymptomsDiary.java:76)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- symptomsDiaryDelete -->
</testsuite> <!-- SymptomsDiary -->
